
spring:
  application:
    name: AllCityTransportAgency

  datasource:
    url: jdbc:postgresql://dpg-d5j34sffte5s73d51sa0-a.oregon-postgres.render.com:5432/transport1
    username: transport
    password: F0aBOLdipfw6x9dFKmHWICSE4ZmDC9mC
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
secreteJwtString: dennis123456789dennis123456789dennis123456789


#
#spring:
#  application:
#    name: AllCityTransportAgency
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/transport1
#    username: postgres
#    password: pushpa@9798
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#server:
#  port: 8080
#
#secreteJwtString: dennis123456789dennis123456789dennis123456789
#
